name: Code style & unit tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - version: "3.11"
            check-formatting: "true"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "poetry"
      - name: Set up Node.js
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          poetry install -n
          poetry run pip install flake8
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Code style
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run black --check awscliv2
          poetry run isort -c awscliv2
      - name: Lint
        run: |
          poetry run flake8 awscliv2
      - name: Typing
        run: |
          poetry run npx pyright
      - name: Test
        run: |
          poetry run pytest
