name: Send coverage report

on:
  push:
    branches:
      - main
    paths:
      - awscliv2/**
      - tests/**
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
      - name: Send coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          poetry run pytest --cov-report term --cov awscliv2
          poetry run codecov
